# Generated by Django 3.2.7 on 2021-09-25 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='name_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.teacher'),
        ),
    ]
