# Generated by Django 3.2.7 on 2021-09-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='newprice',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='course',
            name='numberstudents',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='oldprice',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
    ]
