# Generated by Django 3.2.7 on 2021-09-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210925_2042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='newprice',
            new_name='new_price',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='numberstudents',
            new_name='number_students',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='oldprice',
            new_name='old_price',
        ),
    ]
