# Generated by Django 3.2.7 on 2021-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=50, verbose_name='Tiêu đề')),
                ('pubday', models.DateField(verbose_name='Ngày đăng')),
                ('content', models.CharField(max_length=100, verbose_name='Nội dung')),
            ],
            options={
                'db_table': 'News',
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='headline',
            field=models.CharField(max_length=50, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_price',
            field=models.CharField(default='SOME STRING', max_length=25, verbose_name='Giá mới'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_students',
            field=models.CharField(default='SOME STRING', max_length=50, verbose_name='Số học sinh'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.CharField(default='SOME STRING', max_length=25, verbose_name='Giá cũ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='pubday',
            field=models.DateField(verbose_name='Ngày đăng'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='document',
            name='headline',
            field=models.CharField(max_length=50, verbose_name='Tiêu đề'),
        ),
        migrations.AlterField(
            model_name='document',
            name='pubday',
            field=models.DateField(verbose_name='Ngày đăng'),
        ),
    ]
