# Generated by Django 3.2.7 on 2021-09-26 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210926_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.CharField(default='', max_length=200, verbose_name='Link bài viết'),
        ),
        migrations.AlterField(
            model_name='course',
            name='new_price',
            field=models.CharField(default='', max_length=25, verbose_name='Giá mới'),
        ),
        migrations.AlterField(
            model_name='course',
            name='number_students',
            field=models.CharField(default='', max_length=50, verbose_name='Số học sinh'),
        ),
        migrations.AlterField(
            model_name='course',
            name='old_price',
            field=models.CharField(default='', max_length=25, verbose_name='Giá cũ'),
        ),
    ]
