# Generated by Django 3.2.7 on 2021-09-28 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210927_1000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('infor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='home.course')),
            ],
        ),
    ]
