# Generated by Django 3.2.7 on 2021-09-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_restaurant_inforcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content',
            field=models.CharField(default='', max_length=100, verbose_name='Nội dung khóa học'),
        ),
        migrations.DeleteModel(
            name='InforCourse',
        ),
    ]
