# Generated by Django 3.2.7 on 2021-10-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_document_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30, verbose_name='Họ và tên')),
                ('position', models.CharField(max_length=30, verbose_name='Chuyên ngành')),
                ('description', models.CharField(max_length=100, verbose_name='Mô tả')),
            ],
            options={
                'db_table': 'Trainers',
            },
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='news',
            name='link',
            field=models.CharField(default='', max_length=150, verbose_name='Link bài viết'),
        ),
    ]
