# Generated by Django 3.2.7 on 2021-10-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20211002_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='imagetrainer',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
