# Generated by Django 3.2.7 on 2021-10-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_trainers_imagetrainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainers',
            name='linkin4',
            field=models.CharField(default='', max_length=500, verbose_name='Link bài viết'),
        ),
    ]
