# Generated by Django 3.2.7 on 2021-10-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_trainers_linkin4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainers',
            name='linkin4',
            field=models.CharField(default='', max_length=300, verbose_name='Link bài viết'),
        ),
    ]
