# Generated by Django 3.2.7 on 2021-10-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_trainers_linkin4'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('studentclass', models.CharField(max_length=100)),
                ('studentemail', models.CharField(max_length=100)),
                ('phonebumber', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='trainers',
            name='imagetrainer',
            field=models.ImageField(null=True, upload_to='', verbose_name='Ảnh giảng viên'),
        ),
        migrations.AlterField(
            model_name='trainers',
            name='linkin4',
            field=models.CharField(default='', max_length=300, verbose_name='Link mạng xã hội'),
        ),
    ]
