# Generated by Django 3.2.7 on 2021-10-04 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20211004_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phonebumber',
            new_name='phonenumber',
        ),
    ]
